version: "3"

dotenv:
  - ".env"

tasks:
  default:
    desc: "show all available tasks"
    cmds:
      - task --list-all
    silent: true

  run:
    desc: "start the app"
    cmds:
      - go run ./cmd/main.go
    silent: true

  testenv:
    desc: "do docker-compose file for setup test env"
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - test -f docker-compose.yml
      - test -f .test.env
    cmds:
      - scripts/testenv.sh

  localenv:
    desc: "do docker-compose file for setup test env"
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - test -f docker-compose.yml
      - test -f .env
    cmds:
      - scripts/localenv.sh

  tidy:
    desc: install pkg listed in go.mod
    cmds:
      - go mod tidy

  coverage:
    desc: run unit test and force coverage > 80%
    cmds:
      - ./scripts/coverage.sh

  mock:
    desc: Auto-generate mocks for all interfaces
    cmds:
      - rm -rf test/mocks/* # 💥 Clean old mocks
      - mockery
      - go mod tidy
    silent: false

  deps:
    desc: install dependencies
    cmds:
      - go install github.com/vektra/mockery/v3@v3.4.0
      - go install github.com/wadey/gocovmerge@latest

  keys:
    desc: generate keys
    cmds:
      - ./scripts/gen-key.sh

  generate:
    desc: generate API code from OpenAPI specification
    cmds:
      - ./scripts/gen-api.sh
    deps: [deps]
    preconditions:
      - test -f api.spec.yml

  unit_test:
    desc: run unit test
    cmds:
      - ./scripts/unittest.sh
    preconditions:
      - test -f ./scripts/unittest.sh

  integration_test:
    desc: run integration test
    cmds:
      - ./scripts/integration.sh
    preconditions:
      - test -f ./scripts/integration.sh

  api_test:
    desc: run api test
    cmds:
      - ./scripts/api-test.sh
    preconditions:
      - test -f ./scripts/api-test.sh
