version: '3'

tasks:
  default: 
    desc: 'show all available tasks'
    cmds:
      - task --list-all
    silent: true
  setup:
    desc: 'run script to create required files and dependencies pkg'
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f scripts/init_project.sh
    cmds:
      - scripts/init_project.sh
  run:
    desc: 'start the app'
    cmds:
      - scripts/build.sh
  localenv:
    desc: 'do docker-compose file for setup local env'
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f infra/docker-compose.yml
    cmds:
      - scripts/setup_local_env.sh
  tidy:
    desc: install pkg listed in go.mod
    cmds:
      -  go mod tidy
