version: "3"

dotenv:
  - ".env"

tasks:
  default:
    desc: "show all available tasks"
    cmds:
      - task --list-all
    silent: true

  run:
    desc: "start the app"
    cmds:
      - go run ./cmd/auth-service
    silent: true

  testenv:
    desc: "do docker-compose file for setup test env"
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - test -f environment/docker-compose.yml
    cmds:
      - scripts/testenv.sh

  tidy:
    desc: install pkg listed in go.mod
    cmds:
      - go mod tidy

  coverage:
    desc: run unit test and force coverage > 80%
    cmds:
      - ./scripts/coverage.sh

  mock:
    desc: Auto-generate mocks for all interfaces
    cmds:
      - rm -rf test/mocks/* # 💥 Clean old mocks
      - mockery
      - go mod tidy
    silent: false

  deps:
    desc: install dependencies
    cmds:
      - go install github.com/vektra/mockery/v3@v3.4.0

  keys:
    desc: generate keys
    cmds:
      - ./scripts/gen-key.sh

  generate:
    desc: generate API code from OpenAPI specification
    cmds:
      - ./scripts/gen-api.sh
    deps: [deps]
    preconditions:
      - test -f api.spec.yml
