services:
  postgres:
    image: postgres:16.4-alpine
    container_name: pg_${SERVICE_NAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ../.docker/pg-data:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    networks:
      - localnet
    restart: unless-stopped


networks:
  localnet:
    driver: bridge
