// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"auth-service/internal/model"
	"auth-service/internal/usecase/dto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAccountUsecase creates a new instance of AccountUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountUsecase {
	mock := &AccountUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountUsecase is an autogenerated mock type for the AccountUsecase type
type AccountUsecase struct {
	mock.Mock
}

type AccountUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountUsecase) EXPECT() *AccountUsecase_Expecter {
	return &AccountUsecase_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type AccountUsecase
func (_mock *AccountUsecase) ChangePassword(ctx context.Context, input dto.ChangePasswordInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ChangePasswordInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountUsecase_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type AccountUsecase_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.ChangePasswordInput
func (_e *AccountUsecase_Expecter) ChangePassword(ctx interface{}, input interface{}) *AccountUsecase_ChangePassword_Call {
	return &AccountUsecase_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, input)}
}

func (_c *AccountUsecase_ChangePassword_Call) Run(run func(ctx context.Context, input dto.ChangePasswordInput)) *AccountUsecase_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ChangePasswordInput
		if args[1] != nil {
			arg1 = args[1].(dto.ChangePasswordInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountUsecase_ChangePassword_Call) Return(err error) *AccountUsecase_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountUsecase_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, input dto.ChangePasswordInput) error) *AccountUsecase_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AccountUsecase
func (_mock *AccountUsecase) Register(ctx context.Context, input dto.RegisterInput) (*model.Account, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.RegisterInput) (*model.Account, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.RegisterInput) *model.Account); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.RegisterInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AccountUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.RegisterInput
func (_e *AccountUsecase_Expecter) Register(ctx interface{}, input interface{}) *AccountUsecase_Register_Call {
	return &AccountUsecase_Register_Call{Call: _e.mock.On("Register", ctx, input)}
}

func (_c *AccountUsecase_Register_Call) Run(run func(ctx context.Context, input dto.RegisterInput)) *AccountUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.RegisterInput
		if args[1] != nil {
			arg1 = args[1].(dto.RegisterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountUsecase_Register_Call) Return(account *model.Account, err error) *AccountUsecase_Register_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *AccountUsecase_Register_Call) RunAndReturn(run func(ctx context.Context, input dto.RegisterInput) (*model.Account, error)) *AccountUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}
