// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewAccountHandler creates a new instance of AccountHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountHandler {
	mock := &AccountHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountHandler is an autogenerated mock type for the AccountHandler type
type AccountHandler struct {
	mock.Mock
}

type AccountHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountHandler) EXPECT() *AccountHandler_Expecter {
	return &AccountHandler_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type AccountHandler
func (_mock *AccountHandler) ChangePassword(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// AccountHandler_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type AccountHandler_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *AccountHandler_Expecter) ChangePassword(ctx interface{}) *AccountHandler_ChangePassword_Call {
	return &AccountHandler_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx)}
}

func (_c *AccountHandler_ChangePassword_Call) Run(run func(ctx *gin.Context)) *AccountHandler_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AccountHandler_ChangePassword_Call) Return() *AccountHandler_ChangePassword_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccountHandler_ChangePassword_Call) RunAndReturn(run func(ctx *gin.Context)) *AccountHandler_ChangePassword_Call {
	_c.Run(run)
	return _c
}

// CreateAccount provides a mock function for the type AccountHandler
func (_mock *AccountHandler) CreateAccount(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// AccountHandler_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type AccountHandler_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *AccountHandler_Expecter) CreateAccount(ctx interface{}) *AccountHandler_CreateAccount_Call {
	return &AccountHandler_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx)}
}

func (_c *AccountHandler_CreateAccount_Call) Run(run func(ctx *gin.Context)) *AccountHandler_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AccountHandler_CreateAccount_Call) Return() *AccountHandler_CreateAccount_Call {
	_c.Call.Return()
	return _c
}

func (_c *AccountHandler_CreateAccount_Call) RunAndReturn(run func(ctx *gin.Context)) *AccountHandler_CreateAccount_Call {
	_c.Run(run)
	return _c
}
