// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/DucTran999/auth-service/internal/model"
	"github.com/DucTran999/auth-service/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

type AuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthUseCase) EXPECT() *AuthUseCase_Expecter {
	return &AuthUseCase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type AuthUseCase
func (_mock *AuthUseCase) Login(ctx context.Context, input usecase.LoginInput) (*model.Session, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.LoginInput) (*model.Session, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.LoginInput) *model.Session); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.LoginInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.LoginInput
func (_e *AuthUseCase_Expecter) Login(ctx interface{}, input interface{}) *AuthUseCase_Login_Call {
	return &AuthUseCase_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *AuthUseCase_Login_Call) Run(run func(ctx context.Context, input usecase.LoginInput)) *AuthUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.LoginInput
		if args[1] != nil {
			arg1 = args[1].(usecase.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthUseCase_Login_Call) Return(session *model.Session, err error) *AuthUseCase_Login_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *AuthUseCase_Login_Call) RunAndReturn(run func(ctx context.Context, input usecase.LoginInput) (*model.Session, error)) *AuthUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}
