// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Cache
func (_mock *Cache) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Cache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Cache_Expecter) Close() *Cache_Close_Call {
	return &Cache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Cache_Close_Call) Run(run func()) *Cache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cache_Close_Call) Return(err error) *Cache_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cache_Close_Call) RunAndReturn(run func() error) *Cache_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Del provides a mock function for the type Cache
func (_mock *Cache) Del(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cache_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type Cache_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Cache_Expecter) Del(ctx interface{}, key interface{}) *Cache_Del_Call {
	return &Cache_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *Cache_Del_Call) Run(run func(ctx context.Context, key string)) *Cache_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_Del_Call) Return(err error) *Cache_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cache_Del_Call) RunAndReturn(run func(ctx context.Context, key string) error) *Cache_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Expire provides a mock function for the type Cache
func (_mock *Cache) Expire(ctx context.Context, key string, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cache_Expire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expire'
type Cache_Expire_Call struct {
	*mock.Call
}

// Expire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - expiration time.Duration
func (_e *Cache_Expecter) Expire(ctx interface{}, key interface{}, expiration interface{}) *Cache_Expire_Call {
	return &Cache_Expire_Call{Call: _e.mock.On("Expire", ctx, key, expiration)}
}

func (_c *Cache_Expire_Call) Run(run func(ctx context.Context, key string, expiration time.Duration)) *Cache_Expire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cache_Expire_Call) Return(err error) *Cache_Expire_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cache_Expire_Call) RunAndReturn(run func(ctx context.Context, key string, expiration time.Duration) error) *Cache_Expire_Call {
	_c.Call.Return(run)
	return _c
}

// GetInto provides a mock function for the type Cache
func (_mock *Cache) GetInto(ctx context.Context, key string, dest any) error {
	ret := _mock.Called(ctx, key, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetInto")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, key, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cache_GetInto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInto'
type Cache_GetInto_Call struct {
	*mock.Call
}

// GetInto is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dest any
func (_e *Cache_Expecter) GetInto(ctx interface{}, key interface{}, dest interface{}) *Cache_GetInto_Call {
	return &Cache_GetInto_Call{Call: _e.mock.On("GetInto", ctx, key, dest)}
}

func (_c *Cache_GetInto_Call) Run(run func(ctx context.Context, key string, dest any)) *Cache_GetInto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Cache_GetInto_Call) Return(err error) *Cache_GetInto_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cache_GetInto_Call) RunAndReturn(run func(ctx context.Context, key string, dest any) error) *Cache_GetInto_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type Cache
func (_mock *Cache) Has(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type Cache_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Cache_Expecter) Has(ctx interface{}, key interface{}) *Cache_Has_Call {
	return &Cache_Has_Call{Call: _e.mock.On("Has", ctx, key)}
}

func (_c *Cache_Has_Call) Run(run func(ctx context.Context, key string)) *Cache_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_Has_Call) Return(b bool, err error) *Cache_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Cache_Has_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *Cache_Has_Call {
	_c.Call.Return(run)
	return _c
}

// MissingKeys provides a mock function for the type Cache
func (_mock *Cache) MissingKeys(ctx context.Context, keys ...string) ([]string, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MissingKeys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]string, error)); ok {
		return returnFunc(ctx, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []string); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_MissingKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MissingKeys'
type Cache_MissingKeys_Call struct {
	*mock.Call
}

// MissingKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *Cache_Expecter) MissingKeys(ctx interface{}, keys ...interface{}) *Cache_MissingKeys_Call {
	return &Cache_MissingKeys_Call{Call: _e.mock.On("MissingKeys",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *Cache_MissingKeys_Call) Run(run func(ctx context.Context, keys ...string)) *Cache_MissingKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Cache_MissingKeys_Call) Return(strings []string, err error) *Cache_MissingKeys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Cache_MissingKeys_Call) RunAndReturn(run func(ctx context.Context, keys ...string) ([]string, error)) *Cache_MissingKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Cache
func (_mock *Cache) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Cache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Cache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *Cache_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *Cache_Set_Call {
	return &Cache_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *Cache_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *Cache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Cache_Set_Call) Return(err error) *Cache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Cache_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) error) *Cache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// TTL provides a mock function for the type Cache
func (_mock *Cache) TTL(ctx context.Context, key string) (int64, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Cache_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type Cache_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Cache_Expecter) TTL(ctx interface{}, key interface{}) *Cache_TTL_Call {
	return &Cache_TTL_Call{Call: _e.mock.On("TTL", ctx, key)}
}

func (_c *Cache_TTL_Call) Run(run func(ctx context.Context, key string)) *Cache_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Cache_TTL_Call) Return(n int64, err error) *Cache_TTL_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Cache_TTL_Call) RunAndReturn(run func(ctx context.Context, key string) (int64, error)) *Cache_TTL_Call {
	_c.Call.Return(run)
	return _c
}
