// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Hasher is an autogenerated mock type for the Hasher type
type Hasher struct {
	mock.Mock
}

type Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Hasher) EXPECT() *Hasher_Expecter {
	return &Hasher_Expecter{mock: &_m.Mock}
}

// ComparePasswordAndHash provides a mock function for the type Hasher
func (_mock *Hasher) ComparePasswordAndHash(pass string, hash string) (bool, error) {
	ret := _mock.Called(pass, hash)

	if len(ret) == 0 {
		panic("no return value specified for ComparePasswordAndHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(pass, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(pass, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(pass, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Hasher_ComparePasswordAndHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePasswordAndHash'
type Hasher_ComparePasswordAndHash_Call struct {
	*mock.Call
}

// ComparePasswordAndHash is a helper method to define mock.On call
//   - pass string
//   - hash string
func (_e *Hasher_Expecter) ComparePasswordAndHash(pass interface{}, hash interface{}) *Hasher_ComparePasswordAndHash_Call {
	return &Hasher_ComparePasswordAndHash_Call{Call: _e.mock.On("ComparePasswordAndHash", pass, hash)}
}

func (_c *Hasher_ComparePasswordAndHash_Call) Run(run func(pass string, hash string)) *Hasher_ComparePasswordAndHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Hasher_ComparePasswordAndHash_Call) Return(b bool, err error) *Hasher_ComparePasswordAndHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Hasher_ComparePasswordAndHash_Call) RunAndReturn(run func(pass string, hash string) (bool, error)) *Hasher_ComparePasswordAndHash_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type Hasher
func (_mock *Hasher) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Hasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type Hasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *Hasher_Expecter) HashPassword(password interface{}) *Hasher_HashPassword_Call {
	return &Hasher_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *Hasher_HashPassword_Call) Run(run func(password string)) *Hasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Hasher_HashPassword_Call) Return(s string, err error) *Hasher_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Hasher_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *Hasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}
