// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewHealthHandler creates a new instance of HealthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthHandler {
	mock := &HealthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthHandler is an autogenerated mock type for the HealthHandler type
type HealthHandler struct {
	mock.Mock
}

type HealthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthHandler) EXPECT() *HealthHandler_Expecter {
	return &HealthHandler_Expecter{mock: &_m.Mock}
}

// CheckLiveness provides a mock function for the type HealthHandler
func (_mock *HealthHandler) CheckLiveness(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// HealthHandler_CheckLiveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckLiveness'
type HealthHandler_CheckLiveness_Call struct {
	*mock.Call
}

// CheckLiveness is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *HealthHandler_Expecter) CheckLiveness(ctx interface{}) *HealthHandler_CheckLiveness_Call {
	return &HealthHandler_CheckLiveness_Call{Call: _e.mock.On("CheckLiveness", ctx)}
}

func (_c *HealthHandler_CheckLiveness_Call) Run(run func(ctx *gin.Context)) *HealthHandler_CheckLiveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HealthHandler_CheckLiveness_Call) Return() *HealthHandler_CheckLiveness_Call {
	_c.Call.Return()
	return _c
}

func (_c *HealthHandler_CheckLiveness_Call) RunAndReturn(run func(ctx *gin.Context)) *HealthHandler_CheckLiveness_Call {
	_c.Run(run)
	return _c
}
