// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/DucTran999/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewIUserRepo creates a new instance of IUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserRepo {
	mock := &IUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IUserRepo is an autogenerated mock type for the IUserRepo type
type IUserRepo struct {
	mock.Mock
}

type IUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserRepo) EXPECT() *IUserRepo_Expecter {
	return &IUserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type IUserRepo
func (_mock *IUserRepo) CreateUser(ctx context.Context, user model.User) (*model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (*model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) *model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type IUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *IUserRepo_Expecter) CreateUser(ctx interface{}, user interface{}) *IUserRepo_CreateUser_Call {
	return &IUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *IUserRepo_CreateUser_Call) Run(run func(ctx context.Context, user model.User)) *IUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserRepo_CreateUser_Call) Return(user1 *model.User, err error) *IUserRepo_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *IUserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user model.User) (*model.User, error)) *IUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type IUserRepo
func (_mock *IUserRepo) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserRepo_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type IUserRepo_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *IUserRepo_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *IUserRepo_GetUserByEmail_Call {
	return &IUserRepo_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *IUserRepo_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *IUserRepo_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserRepo_GetUserByEmail_Call) Return(user *model.User, err error) *IUserRepo_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *IUserRepo_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.User, error)) *IUserRepo_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}
