// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/DucTran999/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

type IUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserService) EXPECT() *IUserService_Expecter {
	return &IUserService_Expecter{mock: &_m.Mock}
}

// RegisterUser provides a mock function for the type IUserService
func (_mock *IUserService) RegisterUser(ctx context.Context, userInfo model.User) (*model.User, error) {
	ret := _mock.Called(ctx, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) (*model.User, error)); ok {
		return returnFunc(ctx, userInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.User) *model.User); ok {
		r0 = returnFunc(ctx, userInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = returnFunc(ctx, userInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IUserService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type IUserService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userInfo model.User
func (_e *IUserService_Expecter) RegisterUser(ctx interface{}, userInfo interface{}) *IUserService_RegisterUser_Call {
	return &IUserService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userInfo)}
}

func (_c *IUserService_RegisterUser_Call) Run(run func(ctx context.Context, userInfo model.User)) *IUserService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.User
		if args[1] != nil {
			arg1 = args[1].(model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IUserService_RegisterUser_Call) Return(user *model.User, err error) *IUserService_RegisterUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *IUserService_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, userInfo model.User) (*model.User, error)) *IUserService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}
