// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasher {
	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// ComparePasswordAndHash provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) ComparePasswordAndHash(password string, hash string) (bool, error) {
	ret := _mock.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for ComparePasswordAndHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(password, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(password, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasswordHasher_ComparePasswordAndHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComparePasswordAndHash'
type PasswordHasher_ComparePasswordAndHash_Call struct {
	*mock.Call
}

// ComparePasswordAndHash is a helper method to define mock.On call
//   - password string
//   - hash string
func (_e *PasswordHasher_Expecter) ComparePasswordAndHash(password interface{}, hash interface{}) *PasswordHasher_ComparePasswordAndHash_Call {
	return &PasswordHasher_ComparePasswordAndHash_Call{Call: _e.mock.On("ComparePasswordAndHash", password, hash)}
}

func (_c *PasswordHasher_ComparePasswordAndHash_Call) Run(run func(password string, hash string)) *PasswordHasher_ComparePasswordAndHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PasswordHasher_ComparePasswordAndHash_Call) Return(b bool, err error) *PasswordHasher_ComparePasswordAndHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *PasswordHasher_ComparePasswordAndHash_Call) RunAndReturn(run func(password string, hash string) (bool, error)) *PasswordHasher_ComparePasswordAndHash_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type PasswordHasher
func (_mock *PasswordHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type PasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *PasswordHasher_Expecter) Hash(password interface{}) *PasswordHasher_Hash_Call {
	return &PasswordHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *PasswordHasher_Hash_Call) Run(run func(password string)) *PasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PasswordHasher_Hash_Call) Return(s string, err error) *PasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *PasswordHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *PasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
