// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"auth-service/internal/domain/sessionmodel"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Create(ctx context.Context, session *sessionmodel.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sessionmodel.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *sessionmodel.Session
func (_e *SessionRepository_Expecter) Create(ctx interface{}, session interface{}) *SessionRepository_Create_Call {
	return &SessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *SessionRepository_Create_Call) Run(run func(ctx context.Context, session *sessionmodel.Session)) *SessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sessionmodel.Session
		if args[1] != nil {
			arg1 = args[1].(*sessionmodel.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Create_Call) Return(err error) *SessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, session *sessionmodel.Session) error) *SessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Revoke(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type SessionRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *SessionRepository_Expecter) Revoke(ctx interface{}, sessionID interface{}) *SessionRepository_Revoke_Call {
	return &SessionRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, sessionID)}
}

func (_c *SessionRepository_Revoke_Call) Run(run func(ctx context.Context, sessionID string)) *SessionRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Revoke_Call) Return(err error) *SessionRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *SessionRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
