// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/DucTran999/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionUsecase creates a new instance of SessionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionUsecase {
	mock := &SessionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionUsecase is an autogenerated mock type for the SessionUsecase type
type SessionUsecase struct {
	mock.Mock
}

type SessionUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionUsecase) EXPECT() *SessionUsecase_Expecter {
	return &SessionUsecase_Expecter{mock: &_m.Mock}
}

// DeleteExpiredBefore provides a mock function for the type SessionUsecase
func (_mock *SessionUsecase) DeleteExpiredBefore(ctx context.Context, cutoff time.Time) error {
	ret := _mock.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredBefore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, cutoff)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionUsecase_DeleteExpiredBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredBefore'
type SessionUsecase_DeleteExpiredBefore_Call struct {
	*mock.Call
}

// DeleteExpiredBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *SessionUsecase_Expecter) DeleteExpiredBefore(ctx interface{}, cutoff interface{}) *SessionUsecase_DeleteExpiredBefore_Call {
	return &SessionUsecase_DeleteExpiredBefore_Call{Call: _e.mock.On("DeleteExpiredBefore", ctx, cutoff)}
}

func (_c *SessionUsecase_DeleteExpiredBefore_Call) Run(run func(ctx context.Context, cutoff time.Time)) *SessionUsecase_DeleteExpiredBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionUsecase_DeleteExpiredBefore_Call) Return(err error) *SessionUsecase_DeleteExpiredBefore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionUsecase_DeleteExpiredBefore_Call) RunAndReturn(run func(ctx context.Context, cutoff time.Time) error) *SessionUsecase_DeleteExpiredBefore_Call {
	_c.Call.Return(run)
	return _c
}

// MarkExpiredSessions provides a mock function for the type SessionUsecase
func (_mock *SessionUsecase) MarkExpiredSessions(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MarkExpiredSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionUsecase_MarkExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkExpiredSessions'
type SessionUsecase_MarkExpiredSessions_Call struct {
	*mock.Call
}

// MarkExpiredSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SessionUsecase_Expecter) MarkExpiredSessions(ctx interface{}) *SessionUsecase_MarkExpiredSessions_Call {
	return &SessionUsecase_MarkExpiredSessions_Call{Call: _e.mock.On("MarkExpiredSessions", ctx)}
}

func (_c *SessionUsecase_MarkExpiredSessions_Call) Run(run func(ctx context.Context)) *SessionUsecase_MarkExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionUsecase_MarkExpiredSessions_Call) Return(err error) *SessionUsecase_MarkExpiredSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionUsecase_MarkExpiredSessions_Call) RunAndReturn(run func(ctx context.Context) error) *SessionUsecase_MarkExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSession provides a mock function for the type SessionUsecase
func (_mock *SessionUsecase) ValidateSession(ctx context.Context, sessionID string) (*model.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSession")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionUsecase_ValidateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSession'
type SessionUsecase_ValidateSession_Call struct {
	*mock.Call
}

// ValidateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *SessionUsecase_Expecter) ValidateSession(ctx interface{}, sessionID interface{}) *SessionUsecase_ValidateSession_Call {
	return &SessionUsecase_ValidateSession_Call{Call: _e.mock.On("ValidateSession", ctx, sessionID)}
}

func (_c *SessionUsecase_ValidateSession_Call) Run(run func(ctx context.Context, sessionID string)) *SessionUsecase_ValidateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionUsecase_ValidateSession_Call) Return(session *model.Session, err error) *SessionUsecase_ValidateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionUsecase_ValidateSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*model.Session, error)) *SessionUsecase_ValidateSession_Call {
	_c.Call.Return(run)
	return _c
}
