// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"auth-service/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSessionStore creates a new instance of SessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStore {
	mock := &SessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionStore is an autogenerated mock type for the SessionStore type
type SessionStore struct {
	mock.Mock
}

type SessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionStore) EXPECT() *SessionStore_Expecter {
	return &SessionStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type SessionStore
func (_mock *SessionStore) Get(ctx context.Context, id string) (*model.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionStore_Expecter) Get(ctx interface{}, id interface{}) *SessionStore_Get_Call {
	return &SessionStore_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *SessionStore_Get_Call) Run(run func(ctx context.Context, id string)) *SessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStore_Get_Call) Return(session *model.Session, err error) *SessionStore_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionStore_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Session, error)) *SessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type SessionStore
func (_mock *SessionStore) Refresh(ctx context.Context, id string) (*model.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionStore_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type SessionStore_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionStore_Expecter) Refresh(ctx interface{}, id interface{}) *SessionStore_Refresh_Call {
	return &SessionStore_Refresh_Call{Call: _e.mock.On("Refresh", ctx, id)}
}

func (_c *SessionStore_Refresh_Call) Run(run func(ctx context.Context, id string)) *SessionStore_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStore_Refresh_Call) Return(session *model.Session, err error) *SessionStore_Refresh_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionStore_Refresh_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Session, error)) *SessionStore_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type SessionStore
func (_mock *SessionStore) Save(ctx context.Context, s *model.Session) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Session) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type SessionStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - s *model.Session
func (_e *SessionStore_Expecter) Save(ctx interface{}, s interface{}) *SessionStore_Save_Call {
	return &SessionStore_Save_Call{Call: _e.mock.On("Save", ctx, s)}
}

func (_c *SessionStore_Save_Call) Run(run func(ctx context.Context, s *model.Session)) *SessionStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Session
		if args[1] != nil {
			arg1 = args[1].(*model.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStore_Save_Call) Return(err error) *SessionStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionStore_Save_Call) RunAndReturn(run func(ctx context.Context, s *model.Session) error) *SessionStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
