// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"auth-service/internal/domain/authmodel"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTokenStore creates a new instance of TokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenStore {
	mock := &TokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenStore is an autogenerated mock type for the TokenStore type
type TokenStore struct {
	mock.Mock
}

type TokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenStore) EXPECT() *TokenStore_Expecter {
	return &TokenStore_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type TokenStore
func (_mock *TokenStore) Exists(ctx context.Context, tokenID string) (bool, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenStore_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type TokenStore_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *TokenStore_Expecter) Exists(ctx interface{}, tokenID interface{}) *TokenStore_Exists_Call {
	return &TokenStore_Exists_Call{Call: _e.mock.On("Exists", ctx, tokenID)}
}

func (_c *TokenStore_Exists_Call) Run(run func(ctx context.Context, tokenID string)) *TokenStore_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenStore_Exists_Call) Return(b bool, err error) *TokenStore_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *TokenStore_Exists_Call) RunAndReturn(run func(ctx context.Context, tokenID string) (bool, error)) *TokenStore_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type TokenStore
func (_mock *TokenStore) Revoke(ctx context.Context, userID string, tokenID string) error {
	ret := _mock.Called(ctx, userID, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenStore_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type TokenStore_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenID string
func (_e *TokenStore_Expecter) Revoke(ctx interface{}, userID interface{}, tokenID interface{}) *TokenStore_Revoke_Call {
	return &TokenStore_Revoke_Call{Call: _e.mock.On("Revoke", ctx, userID, tokenID)}
}

func (_c *TokenStore_Revoke_Call) Run(run func(ctx context.Context, userID string, tokenID string)) *TokenStore_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenStore_Revoke_Call) Return(err error) *TokenStore_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenStore_Revoke_Call) RunAndReturn(run func(ctx context.Context, userID string, tokenID string) error) *TokenStore_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type TokenStore
func (_mock *TokenStore) Save(ctx context.Context, device authmodel.DeviceSession) error {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authmodel.DeviceSession) error); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type TokenStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - device authmodel.DeviceSession
func (_e *TokenStore_Expecter) Save(ctx interface{}, device interface{}) *TokenStore_Save_Call {
	return &TokenStore_Save_Call{Call: _e.mock.On("Save", ctx, device)}
}

func (_c *TokenStore_Save_Call) Run(run func(ctx context.Context, device authmodel.DeviceSession)) *TokenStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authmodel.DeviceSession
		if args[1] != nil {
			arg1 = args[1].(authmodel.DeviceSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenStore_Save_Call) Return(err error) *TokenStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenStore_Save_Call) RunAndReturn(run func(ctx context.Context, device authmodel.DeviceSession) error) *TokenStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
