// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"auth-service/internal/domain/accountmodel"
	"auth-service/internal/domain/authmodel"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

type TokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenService) EXPECT() *TokenService_Expecter {
	return &TokenService_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type TokenService
func (_mock *TokenService) Sign(claims authmodel.TokenClaims) (string, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(authmodel.TokenClaims) (string, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(authmodel.TokenClaims) string); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(authmodel.TokenClaims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type TokenService_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - claims authmodel.TokenClaims
func (_e *TokenService_Expecter) Sign(claims interface{}) *TokenService_Sign_Call {
	return &TokenService_Sign_Call{Call: _e.mock.On("Sign", claims)}
}

func (_c *TokenService_Sign_Call) Run(run func(claims authmodel.TokenClaims)) *TokenService_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 authmodel.TokenClaims
		if args[0] != nil {
			arg0 = args[0].(authmodel.TokenClaims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenService_Sign_Call) Return(s string, err error) *TokenService_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenService_Sign_Call) RunAndReturn(run func(claims authmodel.TokenClaims) (string, error)) *TokenService_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// SignPairs provides a mock function for the type TokenService
func (_mock *TokenService) SignPairs(jti string, signAt time.Time, account *accountmodel.Account) (*authmodel.TokenPairs, error) {
	ret := _mock.Called(jti, signAt, account)

	if len(ret) == 0 {
		panic("no return value specified for SignPairs")
	}

	var r0 *authmodel.TokenPairs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time, *accountmodel.Account) (*authmodel.TokenPairs, error)); ok {
		return returnFunc(jti, signAt, account)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Time, *accountmodel.Account) *authmodel.TokenPairs); ok {
		r0 = returnFunc(jti, signAt, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authmodel.TokenPairs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Time, *accountmodel.Account) error); ok {
		r1 = returnFunc(jti, signAt, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_SignPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignPairs'
type TokenService_SignPairs_Call struct {
	*mock.Call
}

// SignPairs is a helper method to define mock.On call
//   - jti string
//   - signAt time.Time
//   - account *accountmodel.Account
func (_e *TokenService_Expecter) SignPairs(jti interface{}, signAt interface{}, account interface{}) *TokenService_SignPairs_Call {
	return &TokenService_SignPairs_Call{Call: _e.mock.On("SignPairs", jti, signAt, account)}
}

func (_c *TokenService_SignPairs_Call) Run(run func(jti string, signAt time.Time, account *accountmodel.Account)) *TokenService_SignPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *accountmodel.Account
		if args[2] != nil {
			arg2 = args[2].(*accountmodel.Account)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenService_SignPairs_Call) Return(tokenPairs *authmodel.TokenPairs, err error) *TokenService_SignPairs_Call {
	_c.Call.Return(tokenPairs, err)
	return _c
}

func (_c *TokenService_SignPairs_Call) RunAndReturn(run func(jti string, signAt time.Time, account *accountmodel.Account) (*authmodel.TokenPairs, error)) *TokenService_SignPairs_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAccessToken provides a mock function for the type TokenService
func (_mock *TokenService) VerifyAccessToken(ctx context.Context, token string) (*authmodel.TokenClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccessToken")
	}

	var r0 *authmodel.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authmodel.TokenClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authmodel.TokenClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authmodel.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_VerifyAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccessToken'
type TokenService_VerifyAccessToken_Call struct {
	*mock.Call
}

// VerifyAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenService_Expecter) VerifyAccessToken(ctx interface{}, token interface{}) *TokenService_VerifyAccessToken_Call {
	return &TokenService_VerifyAccessToken_Call{Call: _e.mock.On("VerifyAccessToken", ctx, token)}
}

func (_c *TokenService_VerifyAccessToken_Call) Run(run func(ctx context.Context, token string)) *TokenService_VerifyAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenService_VerifyAccessToken_Call) Return(tokenClaims *authmodel.TokenClaims, err error) *TokenService_VerifyAccessToken_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *TokenService_VerifyAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*authmodel.TokenClaims, error)) *TokenService_VerifyAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRefreshToken provides a mock function for the type TokenService
func (_mock *TokenService) VerifyRefreshToken(ctx context.Context, token string) (*authmodel.TokenClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRefreshToken")
	}

	var r0 *authmodel.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authmodel.TokenClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authmodel.TokenClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authmodel.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_VerifyRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRefreshToken'
type TokenService_VerifyRefreshToken_Call struct {
	*mock.Call
}

// VerifyRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenService_Expecter) VerifyRefreshToken(ctx interface{}, token interface{}) *TokenService_VerifyRefreshToken_Call {
	return &TokenService_VerifyRefreshToken_Call{Call: _e.mock.On("VerifyRefreshToken", ctx, token)}
}

func (_c *TokenService_VerifyRefreshToken_Call) Run(run func(ctx context.Context, token string)) *TokenService_VerifyRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenService_VerifyRefreshToken_Call) Return(tokenClaims *authmodel.TokenClaims, err error) *TokenService_VerifyRefreshToken_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *TokenService_VerifyRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*authmodel.TokenClaims, error)) *TokenService_VerifyRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
