name: Snyk

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk-security:
    name: snyk-scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
